x-app: &app
  build: .
  restart: always
  env_file:
    - .env
  volumes:
    - .:/app
    - ./media:/app/media
    - ./static:/app/static
  depends_on:
    - db

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: volcann
      POSTGRES_PASSWORD: voliSend13
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    <<: *app
    command: sh -c "python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes: 
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - web

volumes:
  pgdata: