version: "3.8"

x-app: &app
  build: .
  restart: always
  env_file:
    - .env
  volumes:
    - .:/code
    - ./media:/app/media
  depends_on:
    - db

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: volcann
      POSTGRES_PASSWORD: voliSend13
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    <<: *app
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8080
    expose:
      - "8080"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./media:/app/media
    depends_on:
      - web

volumes:
  pgdata:
